# Generated by Django 4.2.3 on 2025-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0002_alter_sports_complex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports_complex',
            name='name',
            field=models.CharField(blank=True, choices=[('P', 'PEDDEM SPORTS COMPLEX'), ('A', 'ATHLETIC STADIUM BAMBOLIM'), ('MP', 'MULTIPURPOSE INDOOR STADIUM (PEDDEM)'), ('SP', 'DR SHYAMA PRASAD MUKHERJEE INDOOR STADIUM'), ('MC', 'MULTIPURPOSE INDOOR CAMPAL'), ('MN', 'MANOHAR PARRIKAR INDOOR STADIUM NAVELIM'), ('MF', 'MULTIPURPOSE HALL FATORDA'), ('IP', 'INDOOR HALL PONDA / SPORTS COMPLEX PONDA'), ('SF', 'SWIMMING POOL FATORDA'), ('AG', 'ASSOLNA GROUND'), ('TM', 'TILAK MAIDAN'), ('AC', 'AGONDA SPORTS COMPLEX'), ('BG', 'BENAULIM GROUND'), ('UG', 'UTORGA GROUND'), ('FM', 'FATORDA MULTIPURPOSE INDOOR STADIUM'), ('PF', 'PJN STADIUM FATORDA'), ('FC', 'FATORDA OPEN SPORTS COMPLEX')], max_length=8, null=True),
        ),
    ]
