# Generated by Django 4.2.3 on 2025-01-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0003_alter_sports_complex_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports_complex',
            options={'verbose_name_plural': 'Sports complexes'},
        ),
    ]
