# Generated by Django 5.1.5 on 2025-02-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0004_alter_sports_complex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports_complex',
            name='facility',
            field=models.CharField(blank=True, choices=[('CT', 'cricket'), ('OFCT', 'open field cricket'), ('HT', 'hockey astro turf'), ('A1', 'atheletic track'), ('A2', 'atheletics'), ('CN', 'conference hall and other rooms'), ('S1', 'Swimming Pool'), ('S2', 'learn to swim Classes'), ('S3', 'learn to swim and life saving'), ('S4', 'Use of Swimming Pool only through booking'), ('FT1', 'football Play Field'), ('FT2', 'D.B Bandodkar Football Ground'), ('GY', 'Gymnasium'), ('GT', 'Gymnastics'), ('IN', 'Indoor Hall'), ('BD', 'Badminton'), ('INBD', 'Indoor Hall Badminton'), ('TT', 'Table Tennis'), ('INTT', 'Indoor Hall Table Tennis'), ('WT', 'Weightlifting'), ('INWT', 'Indoor Weight Lifting'), ('TK', 'Taekwondo'), ('HB', 'Handball'), ('BB', 'Basketball'), ('CH', 'Chess'), ('JD', 'Judo'), ('AC', 'Archery'), ('BX', 'Boxing'), ('RS', 'Roller Skating'), ('OF', 'Open Field(outdoor)'), ('AA', 'All Facilities'), ('OO', 'Open Field Outdoor')], max_length=8, null=True),
        ),
    ]
