# Generated by Django 4.2.3 on 2025-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_facility", "0006_alter_sports_complex_facility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sports_complex",
            options={"verbose_name_plural": "Sports Complexes"},
        ),
        migrations.AlterField(
            model_name="sports_complex",
            name="facility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CT", "Cricket"),
                    ("OFCT", "Open Field Cricket"),
                    ("HT", "Hockey Astro Turf"),
                    ("A1", "Athletic Track"),
                    ("A2", "Athletics"),
                    ("CN", "Conference Hall and Other Rooms"),
                    ("S1", "Swimming Pool"),
                    ("S2", "Learn to Swim Classes"),
                    ("S3", "Learn to Swim and Life Saving"),
                    ("S4", "Use of Swimming Pool Only Through Booking"),
                    ("FT1", "Football Play Field"),
                    ("FT2", "D.B Bandodkar Football Ground"),
                    ("GY", "Gymnasium"),
                    ("GT", "Gymnastics"),
                    ("IN", "Indoor Hall"),
                    ("BD", "Badminton"),
                    ("INBD", "Indoor Hall Badminton"),
                    ("TT", "Table Tennis"),
                    ("INTT", "Indoor Hall Table Tennis"),
                    ("WT", "Weightlifting"),
                    ("INWT", "Indoor Weight Lifting"),
                    ("TK", "Taekwondo"),
                    ("HB", "Handball"),
                    ("BB", "Basketball"),
                    ("CH", "Chess"),
                    ("JD", "Judo"),
                    ("AC", "Archery"),
                    ("BX", "Boxing"),
                    ("RS", "Roller Skating"),
                    ("OF", "Open Field (Outdoor)"),
                    ("AA", "All Facilities"),
                    ("OO", "Open Field Outdoor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sports_complex",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pedem Sports Complex"),
                    ("A", "Athletic Stadium Bambolim"),
                    ("MP", "Multipurpose Indoor Stadium (Pedem)"),
                    ("SP", "Dr. Shyama Prasad Mukherjee Indoor Stadium"),
                    ("MC", "Multipurpose Indoor Campal"),
                    ("MN", "Manohar Parrikar Indoor Stadium Navelim"),
                    ("MF", "Multipurpose Hall Fatorda"),
                    ("IP", "Indoor Hall Ponda / Sports Complex Ponda"),
                    ("SF", "Swimming Pool Fatorda"),
                    ("AG", "Assolna Ground"),
                    ("TM", "Tilak Maidan"),
                    ("AC", "Agonda Sports Complex"),
                    ("BG", "Benaulim Ground"),
                    ("UG", "Utorda Ground"),
                    ("FM", "Fatorda Multipurpose Indoor Stadium"),
                    ("PF", "PJN Stadium Fatorda"),
                    ("FC", "Fatorda Open Sports Complex"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
