# Generated by Django 4.2.3 on 2025-03-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0009_alter_sports_complex_options_and_more'),
    ]

    operations = [
    ]
