# Generated by Django 4.2.3 on 2025-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0010_auto_20250320_1510'),
    ]

    operations = [
    ]
