# Generated by Django 4.2.3 on 2024-12-11 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('GAID', 'Govt Aided Educational Institution'), ('EDINST', 'Educational Institutions'), ('AGSCF', 'Association/Govt/Sports events/Clubs/Federations'), ('OVNR', 'Other village clubs which are not registered to SAG'), ('PSEV', 'Private Sporting events/Tariff for others'), ('HP', 'Hourly Pass'), ('STUD', 'Students'), ('NSTUD', 'Non Students'), ('CA', 'Recognized state Sports Association for conduct of Zonal Championship/Federation Cup/ National Championship/ International Championship or Government / Government aided primary/Secondary / Higher Secondary Schools for Sports Day'), ('CB', 'SAG Registered Sports Club/State Sports Association - League Clubs/ NGOs having annual turnover of less than 3 Lakhs/ Other Educational Institutions for the conduct of any other sporting event (excluding those covered in Cat (A)'), ('CC', 'Sporting event by private party/Organisations/other NGOs (not covered in cat B) or Educational events/Discours/Lectures for/by institutions registered under societies Registrations')], max_length=100)),
                ('type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('HOURLY PASS', 'Hourly Pass'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('ONE REGISTRATION', 'One Registration'), ('MEMBERSHIP RENEWAL', 'Membership Renewal')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sports_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_facility.sports_complex')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True)),
                ('facility', models.CharField(choices=[('CT', 'cricket'), ('OFCT', 'open field cricket'), ('HT', 'hockey astro turf'), ('A1', 'atheletic track'), ('A2', 'atheletics'), ('CN', 'conference hall and other rooms'), ('S1', 'Swimming Pool'), ('S2', 'learn to swim Classes'), ('S3', 'learn to swim and life saving'), ('S4', 'use of swimming pool only through booking'), ('FT1', 'football play field'), ('FT2', 'D.B Bandodkar Football Ground'), ('GY', 'Gymnasium'), ('GT', 'Gymnastics'), ('IN', 'Indoor hall'), ('BD', 'Badminton'), ('INBD', 'indoor hall badminton'), ('TT', 'Table Tennis'), ('INTT', 'indoor hall table tennis'), ('WT', 'weightlifting'), ('INWT', 'indoor weight lifting'), ('TK', 'Taekwondo'), ('HB', 'handball'), ('BB', 'basketball'), ('CH', 'chess'), ('JD', 'Judo'), ('AC', 'archery'), ('BX', 'boxing'), ('RS', 'roller skating'), ('OF', 'Open field(outdoor)'), ('AA', 'all facilities'), ('OO', 'open field outdoor')], max_length=100)),
                ('sports_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_facility.sports_complex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
