# Generated by Django 4.2.3 on 2024-12-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='type',
            field=models.CharField(choices=[('DAILY', 'D'), ('MONTHLY', 'M'), ('HOURLY PASS', 'Hp'), ('QUARTERLY', 'Q'), ('ANNUALLY', 'Y'), ('ONE REGISTRATION', 'Or'), ('MEMBERSHIP RENEWAL', 'Mem')], max_length=20),
        ),
    ]
