# Generated by Django 4.2.3 on 2024-12-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0002_alter_charges_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
