# Generated by Django 4.2.3 on 2024-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0003_remove_booking_additional_info_booking_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.CharField(blank=True, choices=[('GAID', 'Govt Aided Educational Institution'), ('EDINST', 'Educational Institutions'), ('AGSCF', 'Association/Govt/Sports events/Clubs/Federations'), ('OVNR', 'Other village clubs which are not registered to SAG'), ('PSEV', 'Private Sporting events/Tariff for others'), ('HP', 'Hourly Pass'), ('STUD', 'Students'), ('NSTUD', 'Non Students'), ('CA', 'Recognized state Sports Association for conduct of Zonal Championship/Federation Cup/ National Championship/ International Championship or Government / Government aided primary/Secondary / Higher Secondary Schools for Sports Day'), ('CB', 'SAG Registered Sports Club/State Sports Association - League Clubs/ NGOs having annual turnover of less than 3 Lakhs/ Other Educational Institutions for the conduct of any other sporting event (excluding those covered in Cat (A)'), ('CC', 'Sporting event by private party/Organisations/other NGOs (not covered in cat B) or Educational events/Discours/Lectures for/by institutions registered under societies Registrations')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(blank=True, choices=[('DAILY', 'D'), ('MONTHLY', 'M'), ('HOURLY PASS', 'Hp'), ('QUARTERLY', 'Q'), ('ANNUALLY', 'Y'), ('ONE REGISTRATION', 'Or'), ('MEMBERSHIP RENEWAL', 'Mem')], max_length=20, null=True),
        ),
    ]
