# Generated by Django 4.2.3 on 2024-12-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0007_rename_booking_date_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
