# Generated by Django 4.2.3 on 2024-12-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0010_alter_booking_facility_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
    ]
