# Generated by Django 4.2.3 on 2024-12-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0012_booking_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='charges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_booking.charges'),
        ),
    ]
