# Generated by Django 4.2.3 on 2025-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0014_alter_charges_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='type',
            field=models.CharField(choices=[('HALF DAY', 'Hd'), ('FULL DAY', 'Fd'), ('MONTHLY', 'M'), ('HOURLY PASS', 'Hp'), ('QUARTERLY', 'Q'), ('ANNUALLY', 'Y'), ('ONE REGISTRATION', 'Or'), ('MEMBERSHIP RENEWAL', 'Mem')], max_length=20),
        ),
    ]
