# Generated by Django 4.2.3 on 2025-01-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0015_alter_charges_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charges',
            options={'verbose_name_plural': 'Charges'},
        ),
    ]
