# Generated by Django 5.1.5 on 2025-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0016_alter_charges_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AlterField(
            model_name='charges',
            name='group',
            field=models.CharField(choices=[('GAID', 'Govt Aided Educational Institution'), ('EDINST', 'Educational Institutions'), ('AGSCF', 'Association/Govt/Sports events/Clubs/Federations'), ('OVNR', 'Other village clubs which are not registered to SAG'), ('PSEV', 'Private Sporting events/Tariff for others'), ('HP', 'Hourly Pass'), ('STUD', 'Students'), ('NSTUD', 'Non Students'), ('CA', 'category A - Recognized state Sports Association for conduct of Zonal Championship/Federation Cup/ National Championship/ International Championship or Government / Government aided primary/Secondary / Higher Secondary Schools for Sports Day'), ('CB', 'category B - SAG Registered Sports Club/State Sports Association - League Clubs/ NGOs having annual turnover of less than 3 Lakhs/ Other Educational Institutions for the conduct of any other sporting event (excluding those covered in Cat (A))'), ('CC', 'category C - Sporting event by private party/Organisations/other NGOs (not covered in cat B) or Educational events/Discours/Lectures for/by institutions registered under societies Registrations'), ('CD', 'category D - Commercial sporting/NonSporting Event/FilmShooting')], max_length=100),
        ),
    ]
