# Generated by Django 4.2.3 on 2025-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0016_alter_charges_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
