# Generated by Django 4.2.3 on 2025-02-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0017_booking_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
