# Generated by Django 5.1.5 on 2025-02-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0017_booking_booking_end_time'),
        ('facility_booking', '0017_rename_booking_time_booking_end_time_and_more'),
    ]

    operations = [
    ]
