# Generated by Django 5.1.5 on 2025-02-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0018_booking_booking_end_date'),
        ('facility_booking', '0019_rename_end_time_booking_booking_time_and_more'),
    ]

    operations = [
    ]
