# Generated by Django 5.1.5 on 2025-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0020_merge_20250205_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
