# Generated by Django 5.1.5 on 2025-02-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_booking', '0021_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
