export const groupMapping = {
    GAID: 'Govt Aided Educational Institution',
    EDINST: 'Educational Institutions',
    AGSCF: 'Association/Govt/Sports events/Clubs/Federations',
    OVNR: 'Other village clubs which are not registered to SAG',
    PSEV: 'Private Sporting events/Tariff for others',
    HP: 'Hourly Pass',
    STUD: 'Students',
    NSTUD: 'Non Students',
    CA: 'category A -Recognized state Sports Association for conduct of Zonal Championship/Federation Cup/ National Championship/ International Championship or Government / Government aided primary/Secondary / Higher Secondary Schools for Sports Day',
    CB: 'category B -SAG Registered Sports Club/State Sports Association - League Clubs/ NGOs having annual turnover of less than 3 Lakhs/ Other Educational Institutions for the conduct of any other sporting event (excluding those covered in Cat (A)',
    CC: 'category C -Sporting event by private party/Organisations/other NGOs (not covered in cat B) or Educational events/Discours/Lectures for/by institutions registered under societies Registrations',
    CD: 'category D - Commercial sporting/NonSporting Event/FilmShooting',
  };
  
  export const typeMapping = {
    HD: 'HALF DAY',
    FD: 'FULL DAY',
    M: 'MONTHLY',
    HP: 'HOURLY PASS',
    Q: 'QUARTERLY',
    Y: 'ANNUALLY',
    OR: 'ONE REGISTRATION',
    MEM: 'MEMBERSHIP RENEWAL',
  };
  
  export const facilityMapping = {
    CT: 'Cricket',     
    OFCT: 'Open Field Cricket',     
    HT: 'Hockey Astro Turf',     
    A1: 'Athletic Track',     
    A2: 'Athletics',     
    CN: 'Conference Hall And Other Rooms',     
    S1: 'Swimming Pool',     
    S2: 'Learn To Swim Classes',     
    S3: 'Learn To Swim And Life Saving',     
    S4: 'Use Of Swimming Pool Only Through Booking',     
    FT1: 'Football Play Field',     
    FT2: 'D.B Bandodkar Football Ground',     
    GY: 'Gymnasium',     
    GT: 'Gymnastics',     
    IN: 'Indoor Hall',     
    BD: 'Badminton',     
    INBD: 'Indoor Hall Badminton',     
    TT: 'Table Tennis',     
    INTT: 'Indoor Hall Table Tennis',     
    WT: 'Weightlifting',     
    INWT: 'Indoor Weight Lifting',     
    TK: 'Taekwondo',     
    HB: 'Handball',     
    BB: 'Basketball',     
    CH: 'Chess',     
    JD: 'Judo',     
    AC: 'Archery',     
    BX: 'Boxing',     
    RS: 'Roller Skating',     
    OF: 'Open Field(Outdoor)',     
    AA: 'All Facilities',     
    OO: 'Open Field Outdoor'
    
  };
  
  export const complexMapping = {
    P: 'PEDDEM SPORTS COMPLEX',
    A: 'ATHLETIC STADIUM BAMBOLIM',
    MP: 'MULTIPURPOSE INDOOR STADIUM (PEDDEM)',
    SP: 'DR SHYAMA PRASAD MUKHERJEE INDOOR STADIUM',
    MC: 'MULTIPURPOSE INDOOR CAMPAL',
    MN: 'MANOHAR PARRIKAR INDOOR STADIUM NAVELIM',
    MF: 'MULTIPURPOSE HALL FATORDA',
    IP: 'INDOOR HALL PONDA / SPORTS COMPLEX PONDA',
    SF: 'SWIMMING POOL FATORDA',
    AG: 'ASSOLNA GROUND',
    TM: 'TILAK MAIDAN',
    AC: 'AGONDA SPORTS COMPLEX',
    BG: 'BENAULIM GROUND',
    UG: 'UTORGA GROUND',
    FM: 'FATORDA MULTIPURPOSE INDOOR STADIUM',
    PF: 'PJN STADIUM FATORDA',
    FC: 'FATORDA OPEN SPORTS COMPLEX',
  };
  