# Generated by Django 4.2.3 on 2025-03-13 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sports_facility", "0008_alter_sports_complex_uid_camera"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityPeopleCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_count", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people_counts",
                        to="sports_facility.camera",
                    ),
                ),
                (
                    "sports_complex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people_detections",
                        to="sports_facility.sports_complex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility People Count",
                "verbose_name_plural": "Facility People Counts",
            },
        ),
        migrations.CreateModel(
            name="FacilityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("violation_count", models.IntegerField(default=0)),
                ("last_violation", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="sports_facility.camera",
                    ),
                ),
                (
                    "sports_complex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="sports_facility.sports_complex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Alert",
                "verbose_name_plural": "Facility Alerts",
            },
        ),
    ]
