# Generated by Django 4.2.3 on 2025-03-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilityalert",
            options={
                "verbose_name": "Facility Alert",
                "verbose_name_plural": "Facility\xa0Alerts",
            },
        ),
    ]
