# Generated by Django 4.2.3 on 2025-03-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_alter_facilityalert_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilityalert",
            options={
                "verbose_name": "Facility Alert",
                "verbose_name_plural": "Facility Alerts",
            },
        ),
    ]
