# Generated by Django 4.2.3 on 2025-02-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0004_alter_sports_complex_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('stadium_admin', 'Stadium Admin'), ('overall_admin', 'Overall Admin')], default='customer', max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_facility.sports_complex'),
        ),
    ]
