# Generated by Django 5.1.5 on 2025-02-07 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_facility', '0006_alter_sports_complex_facility'),
        ('users', '0003_remove_user_role_remove_user_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('stadium_admin', 'Stadium Admin'), ('overall_admin', 'Overall Admin')], default='customer', max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_facility.sports_complex'),
        ),
    ]
